
version: '3.8'

services:
  devops-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: devops-dashboard
    restart: unless-stopped
    
  # Optional: Add MongoDB for future database needs
  mongodb:
    image: mongo:6.0
    container_name: devops-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - devops_network

networks:
  devops_network:
    driver: bridge

volumes:
  mongodb_data:
